### ISSUE TITLE
Exclamation Triangle Mini (20px) not aligned 

### ISSUE THREAD

**Issue by gambolputty** [tailwindlabs/heroicons#1138]
The exclamation-triangle icon is not centered. 

![image](https://github.com/tailwindlabs/heroicons/assets/8270488/dc9add1c-cb84-4921-a21e-f93536fb2f6a)

**Comment by jamiemlaw** [comment]
I think this is related to [Issue 774](https://github.com/tailwindlabs/heroicons/issues/774) where inside a circle, the triangle previously looked misaligned.

See https://play.tailwindcss.com/JGfRduT1WH for examples

**Comment by sschoger** [comment]
Hey! Because the triangle is bottom heavy it looks misaligned when it is next to other icons or when it is contained in a shape like @jamiemlaw pointed out. Shifting it up makes it optically centered.

Getting icons to look balanced next to one another is definitely one of the trickier parts of icon design 🥵
