### ISSUE TITLE
[Icon Request] Classic floppy disk save icon

### ISSUE THREAD

**Issue by icabetong** [tailwindlabs/heroicons#130]
A classic floppy disk save icon is very useful for forms. 😁

**Comment by aldomendez** [comment]
I created one by self... 
![image](https://user-images.githubusercontent.com/204436/96896511-350fc880-1453-11eb-8c1f-be9c9ecf4459.png)
for some reason doesn't look quite right...

**Comment by asayah-san** [comment]
A little curves on a edges perhaps?

**Comment by ChristopheVanassche** [comment]
The current save-icon looks a bit misleading indeed, would also like to see a classic version of the save-icon.

**Comment by optimizasean** [comment]
The current save icon, I feel it is actually a download file icon.  Since so many people associate the floppy classic as save since it has been and still is being used in many programs and places, I think this should be added in for good UI/UX design since most users will recognize it (still keep the existing icon though!).

Also nice floppy, I think the edge on the right is too long?  Something does look strange, just not sure what 😄
