### ISSUE TITLE
Support pug

### ISSUE THREAD

**Issue by psmyrdek** [tailwindlabs/heroicons#154]
In my products I'm relying heavily on pug template engine. Unfortunately, right now I have to copy an icon as html:
![image](https://user-images.githubusercontent.com/6187417/97727582-df7d9080-1ad0-11eb-86f3-050d3d74e4f1.png)
and then, using [https://html2jade.org/](https://html2jade.org/) I'm converting it to pug.

I'm wondering if it would be a good idea to introduce third format - pug? For sure there would be others that could find this new option useful (considering downloads per day). WDYT?

![image](https://user-images.githubusercontent.com/6187417/97727706-ff14b900-1ad0-11eb-98d1-1c1ef3044bad.png)

**Comment by githubGoblin** [comment]
From my point of view PUG looked really cool but it has one BIG downside -> compatibility. It's kinda like SASS vs SCSS.
At first SASS syntax looks way cooler but then you find out that it's much better to be compatible with old CSS syntax because you may copy any code and it works without rewriting. Same apply to PUG ;)

**Comment by psmyrdek** [comment]
Sure but my questions is about adding it, not removing anything

**Comment by adamwathan** [comment]
Hey! Thanks for the suggestion, going to stick with just SVG/JSX for now, hope that's not a huge bummer 👍  Appreciate it though.
