### ISSUE TITLE
can't import into nextjs

### ISSUE THREAD

**Issue by zebapy** [tailwindlabs/heroicons#177]
Default nextjs build can't seem to import the icons. It's not liking jsx maybe? 

<img width="743" alt="Screen Shot 2020-12-23 at 10 41 54 PM" src="https://user-images.githubusercontent.com/2199845/103058411-140d4600-4570-11eb-84f2-bbc4d75f28ec.png">

https://codesandbox.io/s/next-heroicon-error-t3mp9?file=/pages/index.js 

edit: I realize this is prob because node modules aren't transpiled. Should this repo transpile jsx prepublish?

**Comment by przemyslaw-przylucki** [comment]
@zebapy You need to use an SVG loader

https://stackoverflow.com/questions/55175445/cant-import-svg-into-next-js

**Comment by zebapy** [comment]
In this case, these aren't svg imports, they're react components I thought.

**Comment by adamwathan** [comment]
Hey! The React/Vue components are purposely not documented and not meant to be used yet, we only published them because we were doing some internal testing. We're planning to build proper libraries around this in the near future, but until then I'd recommend using the SVGs with svgr or something similar.
