### ISSUE TITLE
Missing namespace

### ISSUE THREAD

**Issue by Sinnbeck** [tailwindlabs/heroicons#40]
It seems that the dist versions of the icons, are missing the namespace tag?

```
<svg fill="none" viewBox="0 0 24 24" stroke="currentColor">
vs.
<svg xmlns="http://www.w3.org/2000/svg"  fill="none" viewBox="0 0 24 24" stroke="currentColor">

**Comment by adamwathan** [comment]
Hey! Yeah this is deliberate as the namespace is not necessary when the icons are used inline, only when referenced externally as an `img`.

**Comment by Sinnbeck** [comment]
Ah makes sense I suppose. 

We were using the old version of heroicons and had the favicon change depending on what page of the page you were on. Sadly that isn't possible anymore. I dont suppose this will be added back in?

**Comment by CrashyBang** [comment]
This was super useful, does having the namespaces negatively impact the library in anyway?

**Comment by vvo** [comment]
@adamwathan Because of missing xmlns, I got multiple issues when trying to preview the svg:
- in VSCode most extensions will fail at previewing them
- on MacOS (Biggest issue for me), preview won't work, see:

![image](https://user-images.githubusercontent.com/123822/81204672-d9976e80-8fc9-11ea-8a62-f7d9bd57beec.png)

vs

![image](https://user-images.githubusercontent.com/123822/81204695-e320d680-8fc9-11ea-9628-1695c9afe449.png)

Removal of xmlns would be better handled by the user/compiler you're using. For example in React https://react-svgr.com/docs/webpack/ does it by default.

Thoughts?

**Comment by ShaneCorry** [comment]
This "feature" is incredibly annoying for designing, have to edit every icon file before they can be dropped into Adobe XD!
 Perhaps future releases can have a seperate directory with versions of the icons for designers.

**Comment by adamwathan** [comment]
Added it back.

**Comment by vvo** [comment]
@adamwathan quick note: https://heroicons.dev/ do not have the attribute (yet). This is what I mostly use to search/copy svgs (awesome website).
