### ISSUE TITLE
npm ERR! 404  '@heroicons/react@2.0.13' is not in the npm registry

### ISSUE THREAD

**Issue by isaniomoraes** [tailwindlabs/heroicons#874]
Hey,

not sure if it is an issue in NPM registry, but good to check if anyone is having same problems.

Today we got some builds broken on vercel complaining about this heroicons version.

```
npm ERR! 404  '@heroicons/react@2.0.13' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```
<img width="353" alt="Screen Shot 2022-11-08 at 11 03 58" src="https://user-images.githubusercontent.com/3224086/200585131-08d335dc-5901-41e4-ab9a-cdfd6caec1c6.png">

Let me know if I can help with anything.

Thanks!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Pretty sure this is either an npm cache bug (locally) or there is something else going on with npm itself because on the website the version exists: https://www.npmjs.com/package/@heroicons/react/v/2.0.13

When I install it locally I get this:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/1834413/200586382-185d542d-c21c-4ebe-ac75-cb28ed1413aa.png">

Things you can try:
- Try to clean your caches
- Make sure that you are using the official registry and not a private / unofficial one (in that case you probably have to bug that registry)

Sorry I can't be of more help!
