### ISSUE TITLE
@heroicons/react/24/solid"' has no exported member 'XIcon'

### ISSUE THREAD

**Issue by lack-of-gravitas** [tailwindlabs/heroicons#883]
Why is this error occurring?
- package JSON is correct
- import statement appears correct as indicated
![image](https://user-images.githubusercontent.com/10094964/202841153-299a932f-b1f5-449e-a1c0-80173a689c3f.png)

![image](https://user-images.githubusercontent.com/10094964/202841087-3bcc2acf-834f-44e2-b881-12571555e941.png)

**Comment by adamwathan** [comment]
Hey! The error makes sense because there is no icon called `XIcon`.

The only "X" icons are `XCircleIcon` and `XMarkIcon`:

https://unpkg.com/browse/@heroicons/react@2.0.13/24/solid/

<img width="634" alt="image" src="https://user-images.githubusercontent.com/4323180/202848582-f562e5b1-0b5a-4ced-92a0-a7ddc959b259.png">
