### ISSUE TITLE
Half of iris is missing in outline eye-slash.

### ISSUE THREAD

**Issue by micahbuller** [tailwindlabs/heroicons#891]
![eye-iris-not-there](https://user-images.githubusercontent.com/57808486/206783194-7bce2635-90e0-44de-96af-0cc606eb3936.PNG)

**Comment by micahbuller** [comment]
![mini](https://user-images.githubusercontent.com/57808486/206784772-0539c073-e5bc-4bf0-b092-e1b20a683bdb.PNG)
The mini icon seems to have the same issue.

**Comment by sschoger** [comment]
Hey!

This was actually intentional. I always add a little cut out on these icons with a slash to give them a bit of depth. In this case it interfered iris. 

Feather icons and Font Awesome have a similar approach so I'm assuming they ran into the same issue I experienced 😅

<img width="347" alt="CleanShot 2022-12-09 at 16 16 43@2x" src="https://user-images.githubusercontent.com/2652515/206797447-e9b6f346-a1ac-4713-ab31-c6522ac8580a.png">

<img width="959" alt="CleanShot 2022-12-09 at 16 56 24@2x" src="https://user-images.githubusercontent.com/2652515/206802276-3f8cca7e-9800-4b91-8f95-e78c0dd52861.png">

Hope this clarifies everything!
