### ISSUE TITLE
Icon weight solid icons

### ISSUE THREAD

**Issue by ditistommy** [tailwindlabs/heroicons#894]
I've noticed that the solid version of many icons do not have the same visual weight. For example the arrow icons look exactly the same in solid as in outline version. This is disrupting the unity in visual weight for the solid icons. Could these solid icons (for example) get a thicker outline so that the weight is more in line with the other icons?

**Comment by sschoger** [comment]
Hey! This was actually intentional. I considered making the weight thicker many times when designing the set but for a variety of complicated reasons I decided against it. This actually kept me up some nights 😅

I understand in that in the context of browsing the icons and viewing the icons side-by-side they can feel a bit imbalanced but I found that in the context of an application it was a non-issue. 

Sets like Apple SF Symbols, [Material icons](https://fonts.google.com/icons?icon.set=Material+Icons) and [Phosphor icons](https://phosphoricons.com) all take a similar approach. If you're looking for a set that does accomplish what you're asking, check out [Font Awesome](https://fontawesome.com) 👍🏻

Hope this clarifies everything!
