### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by imran-khani** [tailwindlabs/heroicons#980]
### Discussed in https://github.com/tailwindlabs/heroicons/discussions/979

<div type='discussions-op-text'>

<sup>Originally posted by **imran-khani** April 14, 2023</sup>
I am creating one site with a tailwind, and I am a big fan of heoicons by a tailwind. I am just amazed why there are no social icons on heroicons by tailwind labs.</div>

**Comment by adamwathan** [comment]
Hey! Mostly because I don’t think it’s legal to take other company’s logos and include them in a set marked with an MIT license, and I don’t want to complicate the license. We just get social icons directly from the company’s brand pages for our projects. There’s also https://simpleicons.org/ that has tons of them.
